In [2]:
import numpy as np
from sklearn.linear_model import LinearRegression
x = [[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]] 
y = [4, 5, 20, 14, 32, 22, 38, 43]
x, y = np.array(x), np.array(y)
print(x)

[[ 0  1]
 [ 5  1]
 [15  2]
 [25  5]
 [35 11]
 [45 15]
 [55 34]
 [60 35]]


In [3]:
print(y)

[ 4  5 20 14 32 22 38 43]


In [5]:
model = LinearRegression().fit(x, y)
r_sq = model.score(x, y) 
print('coefficient of determination:', r_sq)

coefficient of determination: 0.8615939258756776


In [6]:
print('intercept:', model.intercept_)

intercept: 5.52257927519819


In [7]:
print('slope:', model.coef_)

slope: [0.44706965 0.25502548]


In [8]:
y_pred = model.predict(x)
print('predicted response:', y_pred, sep='\n')

predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [9]:
y_pred = model.intercept_ + np.sum(model.coef_ * x, axis=1) 
print('predicted response:', y_pred, sep='\n')

predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [10]:
x_new = np.arange(10).reshape((-1, 2)) 
print(x_new)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [11]:
y_new = model.predict(x_new) 
print(y_new)

[ 5.77760476  7.18179502  8.58598528  9.99017554 11.3943658 ]
